package Modelo.Hibernate.Object;
// Generated 2 feb. 2021 9:19:47 by Hibernate Tools 5.4.21.Final

/**
 * FotosMunicipios generated by hbm2java
 */
public class FotosMunicipios implements java.io.Serializable {

	private Integer codFoto;
	private Municipios municipios;
	private int tam;
	private byte[] archivo;

	public FotosMunicipios() {
	}

	public FotosMunicipios(Municipios municipios, int tam, byte[] archivo) {
		this.municipios = municipios;
		this.tam = tam;
		this.archivo = archivo;
	}

	public Integer getCodFoto() {
		return this.codFoto;
	}

	public void setCodFoto(Integer codFoto) {
		this.codFoto = codFoto;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public int getTam() {
		return this.tam;
	}

	public void setTam(int tam) {
		this.tam = tam;
	}

	public byte[] getArchivo() {
		return this.archivo;
	}

	public void setArchivo(byte[] archivo) {
		this.archivo = archivo;
	}

}
