package Modelo.Hibernate.Object;
// Generated 2 feb. 2021 9:19:47 by Hibernate Tools 5.4.21.Final

/**
 * Hashes generated by hbm2java
 */
public class Hashes implements java.io.Serializable {

	private String url;
	private String hash;

	public Hashes() {
	}

	public Hashes(String url, String hash) {
		this.url = url;
		this.hash = hash;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

}
