package Modelo.Hibernate.Object;
// Generated 3 feb. 2021 8:26:15 by Hibernate Tools 5.4.21.Final

import java.util.Date;

/**
 * Historico generated by hbm2java
 */
public class Historico implements java.io.Serializable {

	private Integer codHist;
	private Estaciones estaciones;
	private Date fecha;
	private String icaEstacion;

	public Historico() {
	}

	public Historico(Estaciones estaciones, Date fecha, String icaEstacion) {
		this.estaciones = estaciones;
		this.fecha = fecha;
		this.icaEstacion = icaEstacion;
	}

	public Integer getCodHist() {
		return this.codHist;
	}

	public void setCodHist(Integer codHist) {
		this.codHist = codHist;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getIcaEstacion() {
		return this.icaEstacion;
	}

	public void setIcaEstacion(String icaEstacion) {
		this.icaEstacion = icaEstacion;
	}

}
