package Modelo.Hibernate.Object;
// Generated 3 feb. 2021 8:26:15 by Hibernate Tools 5.4.21.Final

/**
 * MunEspNa generated by hbm2java
 */
public class MunEspNa implements java.io.Serializable {

	private String codRelacion;
	private EspaciosNaturales espaciosNaturales;
	private Municipios municipios;

	public MunEspNa() {
	}

	public MunEspNa(String codRelacion, EspaciosNaturales espaciosNaturales, Municipios municipios) {
		this.codRelacion = codRelacion;
		this.espaciosNaturales = espaciosNaturales;
		this.municipios = municipios;
	}

	public String getCodRelacion() {
		return this.codRelacion;
	}

	public void setCodRelacion(String codRelacion) {
		this.codRelacion = codRelacion;
	}

	public EspaciosNaturales getEspaciosNaturales() {
		return this.espaciosNaturales;
	}

	public void setEspaciosNaturales(EspaciosNaturales espaciosNaturales) {
		this.espaciosNaturales = espaciosNaturales;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

}
