package Modelo.Hibernate.Object;
// Generated 19 ene. 2021 10:13:29 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private Integer codProv;
	private String nombre;
	private Set municipioses = new HashSet(0);

	public Provincias() {
	}

	public Provincias(String nombre) {
		this.nombre = nombre;
	}

	public Provincias(String nombre, Set municipioses) {
		this.nombre = nombre;
		this.municipioses = municipioses;
	}

	public Integer getCodProv() {
		return this.codProv;
	}

	public void setCodProv(Integer codProv) {
		this.codProv = codProv;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getMunicipioses() {
		return this.municipioses;
	}

	public void setMunicipioses(Set municipioses) {
		this.municipioses = municipioses;
	}

}
