package Modelo.Hibernate.Object;
// Generated 29 ene. 2021 8:27:12 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer codUser;
	private String nombre;
	private String contra;
	private String pregunta;
	private String respuesta;
	private Set favoritosMuns = new HashSet(0);
	private Set favoritosEsps = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String nombre, String contra, String pregunta, String respuesta) {
		this.nombre = nombre;
		this.contra = contra;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
	}

	public Usuarios(String nombre, String contra, String pregunta, String respuesta, Set favoritosMuns,
			Set favoritosEsps) {
		this.nombre = nombre;
		this.contra = contra;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
		this.favoritosMuns = favoritosMuns;
		this.favoritosEsps = favoritosEsps;
	}

	public Integer getCodUser() {
		return this.codUser;
	}

	public void setCodUser(Integer codUser) {
		this.codUser = codUser;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getContra() {
		return this.contra;
	}

	public void setContra(String contra) {
		this.contra = contra;
	}

	public String getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(String pregunta) {
		this.pregunta = pregunta;
	}

	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	public Set getFavoritosMuns() {
		return this.favoritosMuns;
	}

	public void setFavoritosMuns(Set favoritosMuns) {
		this.favoritosMuns = favoritosMuns;
	}

	public Set getFavoritosEsps() {
		return this.favoritosEsps;
	}

	public void setFavoritosEsps(Set favoritosEsps) {
		this.favoritosEsps = favoritosEsps;
	}

}
