package Modelo.Hibernate.HibernateObject;
// default package
// Generated 12 ene. 2021 18:50:39 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EspaciosNaturales generated by hbm2java
 */
public class EspaciosNaturales implements java.io.Serializable {

	private Integer codEspNatural;
	private Municipios municipios;
	private String nombre;
	private String tipo;
	private double latitud;
	private double longitud;
	private Set favoritosEsps = new HashSet(0);
	private Set fotosEspNaturaleses = new HashSet(0);
	private Set munEspNas = new HashSet(0);

	public EspaciosNaturales() {
	}

	public EspaciosNaturales(Municipios municipios, String nombre, String tipo, double latitud, double longitud) {
		this.municipios = municipios;
		this.nombre = nombre;
		this.tipo = tipo;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	public EspaciosNaturales(Municipios municipios, String nombre, String tipo, double latitud, double longitud,
			Set favoritosEsps, Set fotosEspNaturaleses, Set munEspNas) {
		this.municipios = municipios;
		this.nombre = nombre;
		this.tipo = tipo;
		this.latitud = latitud;
		this.longitud = longitud;
		this.favoritosEsps = favoritosEsps;
		this.fotosEspNaturaleses = fotosEspNaturaleses;
		this.munEspNas = munEspNas;
	}

	public Integer getCodEspNatural() {
		return this.codEspNatural;
	}

	public void setCodEspNatural(Integer codEspNatural) {
		this.codEspNatural = codEspNatural;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(double latitud) {
		this.latitud = latitud;
	}

	public double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(double longitud) {
		this.longitud = longitud;
	}

	public Set getFavoritosEsps() {
		return this.favoritosEsps;
	}

	public void setFavoritosEsps(Set favoritosEsps) {
		this.favoritosEsps = favoritosEsps;
	}

	public Set getFotosEspNaturaleses() {
		return this.fotosEspNaturaleses;
	}

	public void setFotosEspNaturaleses(Set fotosEspNaturaleses) {
		this.fotosEspNaturaleses = fotosEspNaturaleses;
	}

	public Set getMunEspNas() {
		return this.munEspNas;
	}

	public void setMunEspNas(Set munEspNas) {
		this.munEspNas = munEspNas;
	}

}
