package Modelo.Hibernate.HibernateObject;
// default package
// Generated 12 ene. 2021 18:50:39 by Hibernate Tools 5.4.21.Final

/**
 * FavoritosEspId generated by hbm2java
 */
public class FavoritosEspId implements java.io.Serializable {

	private int codEspNatural;
	private int codUser;

	public FavoritosEspId() {
	}

	public FavoritosEspId(int codEspNatural, int codUser) {
		this.codEspNatural = codEspNatural;
		this.codUser = codUser;
	}

	public int getCodEspNatural() {
		return this.codEspNatural;
	}

	public void setCodEspNatural(int codEspNatural) {
		this.codEspNatural = codEspNatural;
	}

	public int getCodUser() {
		return this.codUser;
	}

	public void setCodUser(int codUser) {
		this.codUser = codUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritosEspId))
			return false;
		FavoritosEspId castOther = (FavoritosEspId) other;

		return (this.getCodEspNatural() == castOther.getCodEspNatural())
				&& (this.getCodUser() == castOther.getCodUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodEspNatural();
		result = 37 * result + this.getCodUser();
		return result;
	}

}
