package Modelo.Hibernate.HibernateObject;
// default package
// Generated 12 ene. 2021 18:50:39 by Hibernate Tools 5.4.21.Final

/**
 * FavoritosEstId generated by hbm2java
 */
public class FavoritosEstId implements java.io.Serializable {

	private int codEst;
	private int codUser;

	public FavoritosEstId() {
	}

	public FavoritosEstId(int codEst, int codUser) {
		this.codEst = codEst;
		this.codUser = codUser;
	}

	public int getCodEst() {
		return this.codEst;
	}

	public void setCodEst(int codEst) {
		this.codEst = codEst;
	}

	public int getCodUser() {
		return this.codUser;
	}

	public void setCodUser(int codUser) {
		this.codUser = codUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritosEstId))
			return false;
		FavoritosEstId castOther = (FavoritosEstId) other;

		return (this.getCodEst() == castOther.getCodEst()) && (this.getCodUser() == castOther.getCodUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodEst();
		result = 37 * result + this.getCodUser();
		return result;
	}

}
