package Modelo.Hibernate.HibernateObject;

// default package
// Generated 12 ene. 2021 18:50:39 by Hibernate Tools 5.4.21.Final

/**
 * FavoritosEsp generated by hbm2java
 */
public class FavoritosEsp implements java.io.Serializable {

	private FavoritosEspId id;
	private EspaciosNaturales espaciosNaturales;
	private Usuarios usuarios;

	public FavoritosEsp() {
	}

	public FavoritosEsp(FavoritosEspId id, EspaciosNaturales espaciosNaturales, Usuarios usuarios) {
		this.id = id;
		this.espaciosNaturales = espaciosNaturales;
		this.usuarios = usuarios;
	}

	public FavoritosEspId getId() {
		return this.id;
	}

	public void setId(FavoritosEspId id) {
		this.id = id;
	}

	public EspaciosNaturales getEspaciosNaturales() {
		return this.espaciosNaturales;
	}

	public void setEspaciosNaturales(EspaciosNaturales espaciosNaturales) {
		this.espaciosNaturales = espaciosNaturales;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
