package Modelo.Hibernate.HibernateObject;
// default package
// Generated 12 ene. 2021 18:50:39 by Hibernate Tools 5.4.21.Final

/**
 * FotosEstaciones generated by hbm2java
 */
public class FotosEstaciones implements java.io.Serializable {

	private int codFoto;
	private Estaciones estaciones;
	private String archivo;

	public FotosEstaciones() {
	}

	public FotosEstaciones(int codFoto, Estaciones estaciones, String archivo) {
		this.codFoto = codFoto;
		this.estaciones = estaciones;
		this.archivo = archivo;
	}

	public int getCodFoto() {
		return this.codFoto;
	}

	public void setCodFoto(int codFoto) {
		this.codFoto = codFoto;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public String getArchivo() {
		return this.archivo;
	}

	public void setArchivo(String archivo) {
		this.archivo = archivo;
	}

}
