package Modelo.Hibernate.HibernateObject;
// default package
// Generated 12 ene. 2021 18:50:39 by Hibernate Tools 5.4.21.Final

/**
 * MunEspNaId generated by hbm2java
 */
public class MunEspNaId implements java.io.Serializable {

	private int codMun;
	private int codEspNatural;

	public MunEspNaId() {
	}

	public MunEspNaId(int codMun, int codEspNatural) {
		this.codMun = codMun;
		this.codEspNatural = codEspNatural;
	}

	public int getCodMun() {
		return this.codMun;
	}

	public void setCodMun(int codMun) {
		this.codMun = codMun;
	}

	public int getCodEspNatural() {
		return this.codEspNatural;
	}

	public void setCodEspNatural(int codEspNatural) {
		this.codEspNatural = codEspNatural;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MunEspNaId))
			return false;
		MunEspNaId castOther = (MunEspNaId) other;

		return (this.getCodMun() == castOther.getCodMun()) && (this.getCodEspNatural() == castOther.getCodEspNatural());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodMun();
		result = 37 * result + this.getCodEspNatural();
		return result;
	}

}
