package Modelo.Hibernate.HibernateObject;
// default package
// Generated 12 ene. 2021 18:50:39 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Municipios generated by hbm2java
 */
public class Municipios implements java.io.Serializable {

	private Integer codMun;
	private Provincias provincias;
	private String nombre;
	private Set espaciosNaturaleses = new HashSet(0);
	private Set munEspNas = new HashSet(0);
	private Set estacioneses = new HashSet(0);

	public Municipios() {
	}

	public Municipios(Provincias provincias, String nombre) {
		this.provincias = provincias;
		this.nombre = nombre;
	}

	public Municipios(Provincias provincias, String nombre, Set espaciosNaturaleses, Set munEspNas, Set estacioneses) {
		this.provincias = provincias;
		this.nombre = nombre;
		this.espaciosNaturaleses = espaciosNaturaleses;
		this.munEspNas = munEspNas;
		this.estacioneses = estacioneses;
	}

	public Integer getCodMun() {
		return this.codMun;
	}

	public void setCodMun(Integer codMun) {
		this.codMun = codMun;
	}

	public Provincias getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Provincias provincias) {
		this.provincias = provincias;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getEspaciosNaturaleses() {
		return this.espaciosNaturaleses;
	}

	public void setEspaciosNaturaleses(Set espaciosNaturaleses) {
		this.espaciosNaturaleses = espaciosNaturaleses;
	}

	public Set getMunEspNas() {
		return this.munEspNas;
	}

	public void setMunEspNas(Set munEspNas) {
		this.munEspNas = munEspNas;
	}

	public Set getEstacioneses() {
		return this.estacioneses;
	}

	public void setEstacioneses(Set estacioneses) {
		this.estacioneses = estacioneses;
	}

}
