package Modelo.Hibernate.HibernateObject;
// default package
// Generated 12 ene. 2021 18:50:39 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer codUser;
	private String nombre;
	private String contraseña;
	private String pregunta;
	private String respuesta;
	private Set favoritosEsts = new HashSet(0);
	private Set favoritosEsps = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String nombre, String contraseña, String pregunta, String respuesta) {
		this.nombre = nombre;
		this.contraseña = contraseña;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
	}

	public Usuarios(String nombre, String contraseña, String pregunta, String respuesta, Set favoritosEsts,
			Set favoritosEsps) {
		this.nombre = nombre;
		this.contraseña = contraseña;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
		this.favoritosEsts = favoritosEsts;
		this.favoritosEsps = favoritosEsps;
	}

	public Integer getCodUser() {
		return this.codUser;
	}

	public void setCodUser(Integer codUser) {
		this.codUser = codUser;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getContraseña() {
		return this.contraseña;
	}

	public void setContraseña(String contraseña) {
		this.contraseña = contraseña;
	}

	public String getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(String pregunta) {
		this.pregunta = pregunta;
	}

	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	public Set getFavoritosEsts() {
		return this.favoritosEsts;
	}

	public void setFavoritosEsts(Set favoritosEsts) {
		this.favoritosEsts = favoritosEsts;
	}

	public Set getFavoritosEsps() {
		return this.favoritosEsps;
	}

	public void setFavoritosEsps(Set favoritosEsps) {
		this.favoritosEsps = favoritosEsps;
	}

}
